#!/usr/bin/env bash
if $SHELL_CONFIG_VERBOSE; then echo "Configure shell for git"; fi;


# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	complete -o default -o nospace -F _git g;
fi;


# https://github.com/git/git/blob/master/contrib/completion/git-completion.bash
if [ -f "$HOME/.git-completion.bash" ]; then
    source "$HOME/.git-completion.bash"
fi;


# https://github.com/magicmonty/bash-git-prompt
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source $HOME/.bash-git-prompt/gitprompt.sh
else
# https://gist.github.com/michaelneu/943693f46f7aa249fad2e6841cd918d5
    COLOR_GIT_CLEAN='\[\033[1;30m\]'
    COLOR_GIT_MODIFIED='\[\033[0;33m\]'
    COLOR_GIT_STAGED='\[\033[0;36m\]'
    COLOR_RESET='\[\033[0m\]'

    function git_prompt() {
    if [ -e ".git" ]; then
        branch_name=$(git symbolic-ref -q HEAD)
        branch_name=${branch_name##refs/heads/}
        branch_name=${branch_name:-HEAD}

        echo -n "→ "

        if [[ $(git status 2> /dev/null | tail -n1) = *"nothing to commit"* ]]; then
        echo -n "$COLOR_GIT_CLEAN$branch_name$COLOR_RESET"
        elif [[ $(git status 2> /dev/null | head -n5) = *"Changes to be committed"* ]]; then
        echo -n "$COLOR_GIT_STAGED$branch_name$COLOR_RESET"
        else
        echo -n "$COLOR_GIT_MODIFIED$branch_name*$COLOR_RESET"
        fi

        echo -n " "
    fi
    }

    function prompt() {
    PS1="\u@\h [ \w $(git_prompt)] \$ "
    }

    PROMPT_COMMAND=prompt
fi;
