#!/usr/bin/env bash
if $SHELL_CONFIG_VERBOSE; then echo "Configure shell for pyenv"; fi;

# Add pyenv to PATH
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Initialize pyenv, see: https://github.com/pyenv/pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
